--Table
IF NOT EXISTS(SELECT 1 FROM sysobjects WHERE name = 'TABLE_TESTE' AND xtype = 'U')
BEGIN  
	
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	BEGIN TRANSACTION
	PRINT '--------------------------------------------------'
	PRINT 'ACTION:  CREATE TABLE TABLE_TESTE' 
	PRINT '--------------------------------------------------'
    CREATE TABLE dbo.TABLE_TESTE (
        MAJOR NUMERIC(12,0) NOT NULL,
		MINOR NUMERIC(12,0) NOT NULL,
		REVISION NUMERIC(12,0) NOT NULL,
		BLOCK NUMERIC(12,0) NOT NULL,
        DT_UPDATE DATETIME NOT NULL,
        USUARIO NVARCHAR(256) NULL,
        DATA_BASE NVARCHAR(256) NOT NULL,
		CONSTRAINT PK_TBFR_RELEASE PRIMARY KEY  CLUSTERED 
		(MAJOR,MINOR,REVISION,BLOCK,DATA_BASE)
	);

	IF (@@ERROR<>0) AND (@@TRANCOUNT>0) 
		ROLLBACK TRANSACTION 
	ELSE BEGIN
		INSERT INTO dbo.TBFR_RELEASE (MAJOR,MINOR,REVISION,BLOCK, DT_UPDATE, USUARIO, DATA_BASE) VALUES (0,0,0,0, getdate(), SUSER_SNAME(), 'PLATYPUS')
		COMMIT TRANSACTION
	END
END
ELSE BEGIN 
	EXEC ('DELETE FROM dbo.TBFR_RELEASE  WHERE DATA_BASE = ''PLATYPUS'' AND MINOR = 1  and (SELECT COUNT(1) FROM dbo.TBFR_RELEASE T2 WHERE T2.DATA_BASE = ''PLATYPUS'' AND T2.BLOCK = TBFR_RELEASE.BLOCK) > 1');
	EXEC ('UPDATE dbo.TBFR_RELEASE SET MINOR = 0 WHERE DATA_BASE = ''PLATYPUS'' AND MINOR = 1');
END

GO

--Primary Key
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE type = 'PK' AND  object_id = OBJECT_ID ('PK_TABLE_TESTE'))
BEGIN
	ALTER TABLE BLR_CALCULO_DIF_ALT ADD CONSTRAINT PK_BLR_CALCULO_DIF_ALT PRIMARY KEY CLUSTERED 
	(
		[COD_EMPRESA_FW] ASC,
		[COD_CENARIO] ASC,
		[SEQ_PERIODO] ASC,
		[IND_TIPO] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
END