--Count PK Grouped by specifics tables
SELECT QRY.PKCOLUMN FROM
	(SELECT count(column_name) AS PKCOLUMN
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU ON TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
		AND TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME
		AND KU.table_name IN (
			SELECT name FROM sys.objects WHERE type = 'U'
			AND  object_id IN (
				OBJECT_ID('USERS'),
				OBJECT_ID('PRODUCTS'),
				OBJECT_ID('CLIENTS')
			)
		)
	GROUP BY KU.table_name) QRY
WHERE QRY.PKCOLUMN = 0

--Select all PK from specifics tables
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS TC
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KU ON TC.CONSTRAINT_TYPE = 'PRIMARY KEY'
	AND TC.CONSTRAINT_NAME = KU.CONSTRAINT_NAME
	AND KU.table_name IN (
		SELECT name FROM sys.objects WHERE type = 'U'
		AND  object_id IN (OBJECT_ID('USERS'), OBJECT_ID('PRODUCTS'), OBJECT_ID('CLIENTS'))
	);